In [1]:
file = open('number.txt', 'w')
data ="3,45,83,21"
file.write(data)
file.close()

In [2]:
with open("number.txt", "r") as myfile:
    data = myfile.read().replace('/n', ',')

myfile.close()
print(data[6])

3


In [21]:
my_file = open("number.txt", "a")
my_file.write("The end of the line.\n")
my_file.close()

In [5]:
def CalcPercentGrade (S_1, S_2, S_3, S_4, S_5):
  
    total = S_1 + S_2 + S_3 + S_4 + S_5
    average = total / 5.0
    percentage = (total / 500.0) * 100

    if average >= 90:
        grade = 'A'
    elif average >= 80 and average < 90:
        grade = 'B'
    elif average >= 70 and average < 80:
        grade = 'C'
    elif average >= 60 and average < 70:
        grade = 'D'
    else:
        grade = 'E'


    print ("\nThe Total marks is:   \t", total, "/ 500.00")
    print ("\nThe Average marks is: \t", average)
    print ("\nThe Percentage is:    \t", percentage, "%")
    print ("\nThe Grade is:         \t", grade)
print("Enter the marks of five subjects::")

subject_1 = int (input ())
subject_2 = int (input ())
subject_3 = int (input ())
subject_4 = int (input ())
subject_5 = int (input ())

CalcPercentGrade (subject_1, subject_2, subject_3, subject_4, subject_5)

Enter the marks of five subjects::

The Total marks is:   	 429 / 500.00

The Average marks is: 	 85.8

The Percentage is:    	 85.8 %

The Grade is:         	 B


In [6]:
#  1create a 1d  even number array 
import numpy as np
array=np.arange(0,15,2)
print(array)


[ 0  2  4  6  8 10 12 14]


In [7]:
import numpy as np
array = np.arange(0,10)
print (array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#2Create a 3×3 NumPy array of all Boolean value Trues,False
import  numpy as np
ones=np. ones([3,3])
b=np.ones((3,3),dtype=bool)
print (ones)
print(b)

In [ ]:
#3 Extract all odd numbers from array of 1-10
import numpy as np
C=np.array([1,2,3,4,5,6,7,8,9,10])
array=np.arange(1,13,2)
d=np.where (C%2 == 0)
print(array)
print(d)

In [8]:
#4 Replace all odd numbers in an array of 1-10 with the value -1
e=np.array([1,2,3,4,5,6,7,8,9,10])
f=np.where(e%2 ==0)
e[f]= -1
print (e)


[ 1 -1  3 -1  5 -1  7 -1  9 -1]


In [9]:
# 5 Convert a 1D array to a 2D array with 2 rows
import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarray=array.reshape(3,4)
print(newarray)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
#Create two arrays a and b, stack these two arrays vertically use the  np.dot and np.sum to calculate totals
x=np.array([1,2,3,4,5])
y=np.array([4,5,6,7,8,9])
x=np.concatenate((x,y))
print(x)

[1 2 3 4 5 4 5 6 7 8 9]


In [13]:
#8. In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) – remove all repeating  items present in array b

a=np.array([1,2,3,4,5,7,2,1])
b=np.array([4,5,6,7,8,9,2,1])
c=np.concatenate((a,b))
print(c)
c=np.unique(c)
print(c)

[1 2 3 4 5 7 2 1 4 5 6 7 8 9 2 1]
[1 2 3 4 5 6 7 8 9]


In [14]:
#9 Get all items between 3 and 7 from a and b and sum them together
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7,8,9])
c=np.concatenate((a,b))
print(c)
d=c[(3<=c)&(c<7)]
print(d)
print(sum(d))

[1 2 3 4 5 4 5 6 7 8 9]
[3 4 5 4 5 6]
27
